version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.authc.anonymous.username=anonymous_user
      - xpack.security.authc.anonymous.roles=read_music
      - xpack.security.authc.anonymous.authz_exception=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:+
      - IPC_LOCK
    volumes:
        - ./elastic_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200